### ISSUE TITLE
add -k to curl in installinstallmacos.py to allow for self signed HTTPS repos

### ISSUE THREAD

**Issue by Lotusshaney** [munki/macadmin-scripts#12]
If you have a self signed cert on a SUS repo and you use --catalogurl to send installinstallmacos.py to it for downloads it will fail as curl sees what it considers an invalid cert.  if you at k to the options for curl like this

if show_progress:
        options = '-kfL'
    else:
        options = '-ksfL'

it works fine

**Comment by gregneagle** [comment]
This seems like a dangerous change -- turning off the verification of server SSL certs doesn't seem like a good thing to have hard-coded.

I'd consider a PR that added a new _option_ to turn off SSL verification. Since I don't need this myself I don't know if/when I'd get around to adding such a thing myself.

All PRs would be subject to the same contributor rules as Munki.
