### ISSUE TITLE
Feature Request: Be able to specify title of OS

### ISSUE THREAD

**Issue by cybertunnel** [munki/macadmin-scripts#29]
I am looking at creating a docker image that would help automate keeping our installers and upgrade scripts to the latest version Apple provides.

I was thinking of a few CLI flags like `--os-name Mojave` and then `--latest` would grab the most recent post dated version of that OS.

example: `installinstallmacos.py --catalogurl https:/swscan.apple.com/.../.../... --seedprogram CustomerSeed --os-name Mojave --latest`
The above command will automatically assume I want Mojave, grab all versions of "Mojave" and not "Mojave Beta" and then compare the post dates for the most recent version and use that.

The whole objective here is for it to be automation friendly.

**Comment by grahampugh** [comment]
@cybertunnel You could take a look at my fork of `installinstallmacos.py`. Those features are already built in. https://github.com/grahampugh/macadmin-scripts

And the wrapper script, https://github.com/grahampugh/erase-install, allows you to move the downloaded installer to any path you wish.

**Comment by cybertunnel** [comment]
@grahampugh I just took a look at the changes in the code and saw you check to see if it is a VM. Have you checked to see if this runs on Linux VMs? That's sadly the place it will live in the CI integration.

**Comment by grahampugh** [comment]
@cybertunnel There are parts of my fork that determine which kind of installer will work on the client on which it is running, so they will not work on a non-macOS system. 

I’d bee surprised if the original script can compile the installer app on a non-macOS system either, since it makes a sparseimage or a dmg. I’ve not heard of it being run on anything other than macOS, but I’ll defer to Greg’s input on that.

**Comment by gregneagle** [comment]
It not only makes a disk image, it relies on Apple's installer at /usr/sbin/installer. You'd have to completely re-implement Apple's installer (which I am fairly certain is closed-source) on Linux.
