### ISSUE TITLE
installinstallmacos.py fails on 10.13.6 with Mojave release

### ISSUE THREAD

**Issue by SanderGit** [munki/macadmin-scripts#5]
Related to issue #3 (installation failed)

`Making empty sparseimage...
installer: Error - ERROR_F236DD3E91
Command '['/usr/sbin/installer', '-pkg', './content/downloads/49/44/041-08708/vtip954dc6zbkpdv16iw18jmilcqdt8uot/041-08708.English.dist', '-target', '/private/tmp/dmg.NrDwGz']' returned non-zero exit status 1`

**Comment by SanderGit** [comment]
`installer: Error - ERROR_F236DD3E91`

**Comment by bmike** [comment]
Hi @SanderGit - I believe this is the intended behavior when you download a forked version of the installer on a physical machine. When there are builds that depend on the hardware, after you've downloaded the components, this script runs the actually installer process to assemble the image.

Have a look at the [readme](https://github.com/munki/macadmin-scripts/edit/master/README.md) where it discusses this error and using a VM to run the script so that the check for a "forked" installer doesn't run and produce the error you report.

**Comment by gregneagle** [comment]
@bmike Product 041-08708 is the release version of the Mojave installer, which is not forked. It is possible, however, that he is running `installinstallmacos.py` on hardware that is not supported by Mojave, which _would_ result in an install failure.

**Comment by SanderGit** [comment]
@gregneagle Correct. That is my case. Thanks for clarifying. It was my assumption that e.g. when specifying --raw, the script would only build the installer and not try to launch it. I now re-read the README and understand that it does not work that way. I have found a workaround (the utility from dosdude1).

**Comment by gregneagle** [comment]
It does only build the installer. It does not run it.
