### ISSUE TITLE
10.15.7 fails to download.

### ISSUE THREAD

**Issue by gregdeichler** [munki/macadmin-scripts#71]
10.15.7 fails to download. 

Downloading https://swdist.apple.com/content/downloads/20/55/001-51042-A_2EJTJOSUC2/rsvf13iphg5lvcqcysqcarv8cvddq8igek/RecoveryHDMetaDmg.pkm...
Traceback (most recent call last):
  File "./installinstallmacos.py", line 629, in <module>
    main()
  File "./installinstallmacos.py", line 583, in main
    product_info[product_id]['BUILD']))
KeyError: u'BUILD'

**Comment by gregneagle** [comment]
Was successful here. Make sure you have the current script; it was updated this week to react to Apple changes.

**Comment by 1alessandro1** [comment]
Have a similar issue, i've tried both your version and the fork from grahampugh

This Mac:
Model Identifier : MacBookPro15,2

Bridge ID        : None
Board ID         : Mac-(censored)
OS Version       : 10.15.7
Build ID         : 19H2

 #  ProductID       Version    Build    Post Date   Title                          
 1  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 2  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 3  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 4  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
 5  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 6  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
 7  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
 8  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 9  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
10  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
11  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 

Choose a product to download (1-11): 6
** Resuming transfer from byte position 1584
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 3147356
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 5983436180
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 799367
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 2020
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 1904885
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 188909334
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 10752327
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 328
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 26860
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
** Resuming transfer from byte position 85777558
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Making empty sparseimage...
installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.mhSyoY
2020-09-27 21:50:56.126 installer[3300:171464] Package /Users/Shared/content/downloads/20/55/001-51042-A_2EJTJOSUC2/rsvf13iphg5lvcqcysqcarv8cvddq8igek/InstallESDDmg.pkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).
installer: The install failed. (The Installer could not install the software because there was no software found to install. The Installer could not install the software.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/20/55/001-51042-A_2EJTJOSUC2/rsvf13iphg5lvcqcysqcarv8cvddq8igek/001-51042.English.dist', u'-target', '/private/tmp/dmg.mhSyoY']' returned non-zero exit status 1
Product installation failed.

**Comment by gregneagle** [comment]
Again -- works as expected here (even tried it again within the last hour). I'd look at local issues causing partial/corrupt downloads. Remove the content directory and try again.
