### ISSUE TITLE
installinstallmacos - Downloading Mojave 18a391 results in device being enrolled in Developer Program

### ISSUE THREAD

**Issue by n0brainer** [munki/macadmin-scripts#9]
I used the script to download the mojave installer (from both 10.13 and 10.14), then put it into jamf composer to drop into the applications folder for our upgrade process.  Everything installs and is fine except that the machines are then enrolled in the developer program.  Confirmed on the jamf nation boards that at least one other person is seeing similar behavior.

I downloaded the installed from the mac app store and ran it through jamf composer and then through the upgrade package and the machine was not enrolled in the beta.

<img width="780" alt="screen shot 2018-10-01 at 10 57 59 am" src="https://user-images.githubusercontent.com/2116991/46359352-b27afd00-c62e-11e8-81a6-d86301c54a51.png">
<img width="780" alt="screen shot 2018-10-01 at 10 58 14 am" src="https://user-images.githubusercontent.com/2116991/46359353-b27afd00-c62e-11e8-92e1-75e79d56f558.png">

**Comment by gregneagle** [comment]
This is almost certainly because of an odd tagging mechanism Apple put in place during the Mojave betas. You can probably work around it one of two ways:

1) Use the --catalogurl option and point the tool to the non-seed catalog:
```./installinstallmacos.py --catalogurl https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz```

2) Mount the dmg, copy the Install macOS Mojave.app out of it and remove the `SeedProgram` extended attribute from the app: `xattr -d SeedProgram /path/to/Install\ macOS\ Mojave.app`, then do whatever you need to import the app into Jamf.

You can of course remove any already-deployed machine from the Developer Seed program like so: `sudo softwareupdate --clear-catalog`, which will reset it to the default software update catalog.

**Comment by Lotusshaney** [comment]
Greg your a genius as always :)

**Comment by gregneagle** [comment]
I've just changed the behavior of `installinstallmacos.py` to use the default sucatalog by, well, by default. You can use the --catalogurl or --seedprogram options to point to other catalogs.
